### ISSUE TITLE
symbol lookup error ... undefined symbol on Gadi

### ISSUE THREAD

**Issue by penguian** [payu-org/payu#222] opened 2020-02-05 04:38 UTC
When running a rescaled version of the `1deg_jra55_ryf` of ACCESS-OM2 on Gadi, from directory `/scratch/fp0/pcl900/access-om2/access-om2-gadi-repro-flags-fixed/control/1deg_jra55_ryf`, using `/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.01/bin/payu` from `conda/analysis3-unstable` in `/g/data3/hh5/public/modules`, this results in the error:
```
/scratch/fp0/pcl900/access-om2/work/1deg_jra55_ryf/atmosphere/yatm_59c9cb4-modified.exe: symbol lookup error: /scratch/fp0/pcl900/access-om2/work/1deg_jra55_ryf/atmosphere/yatm_59c9cb4-modified.exe: undefined symbol: netcdf_mp_nf90_open_
```
A workaround is to add 
```
-v MODULE_VERSION=v4.3.0,MODULEPATH=/g/data3/hh5/public/modules:/apps/Modules/restricted-modulefiles/z00:/opt/Modules/modulefiles:/opt/Modules/v4.3.0/modulefiles:/apps/Modules/modulefiles
```
to `qsub-flags` in `config.yaml`.

**Comment by aekiss** [comment] 2020-02-05 05:27
This is a duplicate of this issue - let's consolidate discussion there
https://github.com/payu-org/payu/issues/221

**Closed** 2020-02-05 05:36 UTC
