### ISSUE TITLE
payu collate not collating restart although restart: true in config.yaml 1deg_jra55_iaf

### ISSUE THREAD

**Issue by hakaseh** [payu-org/payu#320] opened 2021-11-22 23:13 UTC
I read https://github.com/payu-org/payu/issues/275 and understand that the latest ACCESS-OM2 control /experiment should collate restart files automatically with `restart: true` in `config.yaml`. But I can't collate restart files in my directory: `/scratch/v45/hh0162/access-om2-cycle4/control/1deg_jra55_iamip2_his`

I'd like to collate restart files in `archive/restart000`. I have tried both `payu collate` and `payu collate -d restart000` but no success so far. There were no error messages for these jobs:
```
Moving log 1deg_jra55_ia_c.o31579143
Moving log 1deg_jra55_ia_c.e31579143
Moving log 1deg_jra55_ia_c.e31578932
Moving log 1deg_jra55_ia_c.o31578932
```
Could you please take a look?

**Comment by aidanheerdegen** [comment] 2021-11-23 00:22
Sounds like a duplicate of #316 

Can you try the latest version in `conda/analysis3-unstable` and see if that fixes your issue.

**Comment by hakaseh** [comment] 2021-11-23 00:41
ahh yes, that fixed the issue! 
thanks @aidanheerdegen

**Comment by hakaseh** [comment] 2021-11-23 23:20
@aidanheerdegen where should I define `module load conda/analysis3-unstable`? I defined it in my `~/.bash_profile` but my test run today indicates it was not used (i.e. the collation of restart files did not happen automatically).

**Comment by aidanheerdegen** [comment] 2021-11-24 00:23
You can find which version of `payu` you're using with
```
which payu
```
Maybe also check if you have a version of `payu` installed locally in `~/.local`.

If none of that helps msg me on slack with details about your control directory and where it isn't working for you.

**Comment by hakaseh** [comment] 2021-11-24 00:31
`which payu` gives
 `/g/data3/hh5/public/apps/miniconda3/envs/analysis3-21.10/bin/payu`

no `payu` is installed in `~/.local`.

i'll message you on slack.

**Closed** 2021-11-24 03:25 UTC
